### ISSUE TITLE
PL2 can't boot halium-boot.img with Enigma kernel

### ISSUE THREAD

**Issue by nouveau-nvc0** [ubports-nokia-sdm660/documentation#2]
After flashing the new `halium-boot.img` (`fastboot flash boot halium-boot.img`) boot hangs on Android One logo. Force rebootmultiply times has no effect.
UBPorts can boot with after flasing old `halium-boot.img` with kernel from LineageOS.
How can I debug it and see dmesg logs?

**Comment by kiam001** [comment]
same problem i have on my PL2

**Comment by Sid127** [comment]
It was an issue with the kernel source at that time. Do continue using the older boot image, I am working on a newer kernel for the devices but am currently occupied with Android 12
